Repository sonata-project/SonataCoreBundle, pull requests merged in 2018-02, with the labels that each got.

#521 Update templates paths in docs
  docs/reference/flash_messages.rst
  docs/reference/form_types.rst
Labels: docs

#522 Minor composer improvements
  composer.json
Labels: pedantic

#523 Make services public
  src/Resources/config/core.xml
Labels: patch
