Repository sonata-project/SonataCoreBundle, pull requests merged in 2018-10, with the labels that each got.

#571 Deprecated old classes
  src/Command/SonataDumpDoctrineMetaCommand.php
  src/Exception/InvalidParameterException.php
Labels: minor

#573 Removed deprecated classes
  docs/index.rst
  docs/reference/command.rst
  src/Command/SonataDumpDoctrineMetaCommand.php
  src/Exception/InvalidParameterException.php
Labels: major

#572 Deprecated doctrine classes
  UPGRADE-3.x.md
  composer.json
  src/Model/Adapter/AdapterChain.php
  src/Model/Adapter/AdapterInterface.php
  src/Model/Adapter/DoctrineORMAdapter.php
  src/Model/Adapter/DoctrinePHPCRAdapter.php
  src/Model/BaseDocumentManager.php
  src/Model/BaseEntityManager.php
  src/Model/BaseManager.php
  src/Model/BasePHPCRManager.php
  src/Model/ManagerInterface.php
  src/Model/PageableManagerInterface.php
  src/Resources/config/model_adapter.xml
  src/Test/EntityManagerMockFactory.php
  tests/Fixtures/Entity/EntityManager.php
  tests/Fixtures/Model/DocumentManager.php
  tests/Fixtures/Model/Manager.php
  tests/Model/Adapter/AdapterChainTest.php
  tests/Model/Adapter/DoctrineORMAdapterTest.php
  tests/Model/Adapter/DoctrinePHPCRAdapterTest.php
  tests/Model/BaseDocumentManagerTest.php
  tests/Model/BaseEntityManagerTest.php
  tests/Model/BaseManagerTest.php
Labels: minor

#543 DateTimePicker format
  src/Form/Type/BasePickerType.php
  src/Form/Type/DatePickerType.php
  src/Form/Type/DateTimePickerType.php
  tests/Form/Type/BasePickerTypeTest.php
  tests/Form/Type/DatePickerTypeTest.php
  tests/Form/Type/DateTimePickerTypeTest.php
Labels: patch
