Repository sonata-project/SonataCoreBundle, pull requests merged in 2018-12, with the labels that each got.

#599 Fix fatal error related to missing retrurn statement in FlashMessageExtension
  src/CoreBundle/Twig/Extension/FlashMessageExtension.php
Labels: bug, patch

#606 Use aliasing instead of inheritance
  src/CoreBundle/Component/Status/StatusClassRendererInterface.php
Labels: patch

#610 Apply aliasing over extension wherever we can
  src/CoreBundle/Date/MomentFormatConverter.php
  src/CoreBundle/FlashMessage/FlashManager.php
  src/CoreBundle/Form/DataTransformer/BooleanTypeToBooleanTransformer.php
  src/CoreBundle/Form/Type/BaseDoctrineORMSerializationType.php
  src/CoreBundle/Form/Type/BasePickerType.php
  src/CoreBundle/Form/Type/BaseStatusType.php
  src/CoreBundle/Form/Type/BooleanType.php
  src/CoreBundle/Form/Type/CollectionType.php
  src/CoreBundle/Form/Type/DateRangePickerType.php
  src/CoreBundle/Form/Type/DateRangeType.php
  src/CoreBundle/Form/Type/DateTimeRangePickerType.php
  src/CoreBundle/Form/Type/DateTimeRangeType.php
  src/CoreBundle/Form/Type/EqualType.php
  src/CoreBundle/Form/Type/ImmutableArrayType.php
  src/CoreBundle/Model/Adapter/AdapterChain.php
  src/CoreBundle/Model/Adapter/AdapterInterface.php
  src/CoreBundle/Model/Adapter/DoctrineORMAdapter.php
  src/CoreBundle/Model/Adapter/DoctrinePHPCRAdapter.php
  src/CoreBundle/Model/BaseDocumentManager.php
  src/CoreBundle/Model/BaseEntityManager.php
  src/CoreBundle/Model/BaseManager.php
  src/CoreBundle/Model/BasePHPCRManager.php
  src/CoreBundle/Model/ManagerInterface.php
  src/CoreBundle/Model/PageableManagerInterface.php
  src/CoreBundle/Serializer/BaseSerializerHandler.php
  src/CoreBundle/Serializer/SerializerHandlerInterface.php
  src/CoreBundle/Test/AbstractWidgetTestCase.php
  src/CoreBundle/Test/EntityManagerMockFactory.php
  src/CoreBundle/Twig/Extension/DeprecatedTemplateExtension.php
  src/CoreBundle/Twig/Extension/FlashMessageRuntime.php
  src/CoreBundle/Twig/Extension/FormTypeExtension.php
  src/CoreBundle/Twig/Extension/StatusRuntime.php
  src/CoreBundle/Twig/Extension/TemplateExtension.php
  src/CoreBundle/Twig/Node/DeprecatedTemplateNode.php
  src/CoreBundle/Twig/Node/TemplateBoxNode.php
  src/CoreBundle/Twig/TokenParser/DeprecatedTemplateTokenParser.php
  src/CoreBundle/Twig/TokenParser/TemplateBoxTokenParser.php
  src/CoreBundle/Validator/Constraints/InlineConstraint.php
  src/CoreBundle/Validator/ErrorElement.php
  src/CoreBundle/Validator/InlineValidator.php
  tests/CoreBundle/Validator/Constraints/InlineConstraintTest.php
  tests/CoreBundle/Validator/ErrorElementTest.php
Labels: patch

#617 Trick Composer into generating class maps
  src/CoreBundle/Component/Status/StatusClassRendererInterface.php
  src/CoreBundle/Date/MomentFormatConverter.php
  src/CoreBundle/FlashMessage/FlashManager.php
  src/CoreBundle/Form/DataTransformer/BooleanTypeToBooleanTransformer.php
  src/CoreBundle/Form/Type/BaseDoctrineORMSerializationType.php
  src/CoreBundle/Form/Type/BasePickerType.php
  src/CoreBundle/Form/Type/BaseStatusType.php
  src/CoreBundle/Form/Type/BooleanType.php
  src/CoreBundle/Form/Type/CollectionType.php
  src/CoreBundle/Form/Type/DateRangePickerType.php
  src/CoreBundle/Form/Type/DateRangeType.php
  src/CoreBundle/Form/Type/DateTimeRangePickerType.php
  src/CoreBundle/Form/Type/DateTimeRangeType.php
  src/CoreBundle/Form/Type/EqualType.php
  src/CoreBundle/Form/Type/ImmutableArrayType.php
  src/CoreBundle/Model/Adapter/AdapterChain.php
  src/CoreBundle/Model/Adapter/AdapterInterface.php
  src/CoreBundle/Model/Adapter/DoctrineORMAdapter.php
  src/CoreBundle/Model/Adapter/DoctrinePHPCRAdapter.php
  src/CoreBundle/Model/BaseDocumentManager.php
  src/CoreBundle/Model/BaseEntityManager.php
  src/CoreBundle/Model/BaseManager.php
  src/CoreBundle/Model/BasePHPCRManager.php
  src/CoreBundle/Model/ManagerInterface.php
  src/CoreBundle/Serializer/BaseSerializerHandler.php
  src/CoreBundle/Serializer/SerializerHandlerInterface.php
  src/CoreBundle/Test/AbstractWidgetTestCase.php
  src/CoreBundle/Test/EntityManagerMockFactory.php
  src/CoreBundle/Twig/Extension/DeprecatedTemplateExtension.php
  src/CoreBundle/Twig/Extension/FlashMessageRuntime.php
  src/CoreBundle/Twig/Extension/FormTypeExtension.php
  src/CoreBundle/Twig/Extension/StatusRuntime.php
  src/CoreBundle/Twig/Extension/TemplateExtension.php
  src/CoreBundle/Twig/Node/DeprecatedTemplateNode.php
  src/CoreBundle/Twig/Node/TemplateBoxNode.php
  src/CoreBundle/Twig/TokenParser/DeprecatedTemplateTokenParser.php
  src/CoreBundle/Twig/TokenParser/TemplateBoxTokenParser.php
  src/CoreBundle/Validator/Constraints/InlineConstraint.php
  src/CoreBundle/Validator/ErrorElement.php
  src/CoreBundle/Validator/InlineValidator.php
Labels: critical, patch

#630 Add missing interface autoload
  src/Twig/Status/StatusClassRendererInterface.php
Labels: patch

#633 Use the correct function to trigger autoload
  src/CoreBundle/Serializer/SerializerHandlerInterface.php
Labels: pedantic

#634 Add missing trick to appear in the classmap
  src/CoreBundle/Model/PageableManagerInterface.php
Labels: patch

#636 Fixed wrong form namespaces
  src/CoreBundle/Resources/config/form_types.xml
Labels: patch

#639 [Docs] use App instead of AppBundle
  docs/reference/doctrine_base_manager.rst
  docs/reference/form_types.rst
  docs/reference/serialization.rst
Labels: docs
