Repository sonata-project/SonataCoreBundle, pull requests merged in 2019-01, with the labels that each got.

#648 Use new exporter namespaces
  composer.json
  src/CoreBundle/Exporter/Exporter.php
  tests/CoreBundle/Exporter/ExporterTest.php
Labels: patch

#650 Add missing conditional statement
  src/CoreBundle/Validator/Constraints/InlineConstraint.php
Labels: patch

#657 Feature/batch flashmessages
  docs/images/collapsed_flashmessage.png
  docs/images/expanded_flashmessage.png
  docs/images/normal_flashmessage.png
  docs/reference/flash_messages.rst
  src/CoreBundle/Resources/public/css/flashmessage.css
  src/CoreBundle/Resources/public/js/base.js
  src/CoreBundle/Resources/translations/SonataCoreBundle.de.xliff
  src/CoreBundle/Resources/translations/SonataCoreBundle.en.xliff
  src/CoreBundle/Resources/views/FlashMessage/render.html.twig
Labels: minor

#660 fix risky tests
  src/CoreBundle/Test/XliffValidatorTestCase.php
Labels: pedantic

#663 Extend the TestCase class
  tests/CoreBundle/DependencyInjection/ConfigurationTest.php
Labels: pedantic
