Repository sonata-project/SonataCoreBundle, pull requests merged in 2019-09, with the labels that each got.

#712 Update `composer.json` in order to tell that the package is abandoned
  composer.json
Labels: pedantic

#710 Add deprecation note to issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#711 Add deprecation note at `README.md`
  README.md
Labels: docs

#716 Fixed signature of InlineConstraint::__sleep
  src/Form/Validator/Constraints/InlineConstraint.php
Labels: patch
