Repository sonata-project/SonataCoreBundle, pull requests merged in 2020-04, with the labels that each got.

#735 Remove DatagridBundle dependency
  composer.json
Labels: minor

#738 Apply latest cs fixes from php-cs-fixer
  src/CoreBundle/Form/EventListener/FixCheckboxDataListener.php
  src/CoreBundle/Form/EventListener/ResizeFormListener.php
  src/Form/Type/DateRangeType.php
  src/Form/Type/DateTimeRangeType.php
  src/Form/Type/EqualType.php
  src/Form/Validator/ErrorElement.php
Labels: critical, pedantic

#737 Move serializer to form directory
  src/CoreBundle/DependencyInjection/SonataCoreExtension.php
  src/CoreBundle/Serializer/BaseSerializerHandler.php
  src/CoreBundle/Serializer/SerializerHandlerInterface.php
  src/Form/Serializer/BaseSerializerHandler.php
  src/Form/Serializer/SerializerHandlerInterface.php
  src/Serializer/BaseSerializerHandler.php
  src/Serializer/SerializerHandlerInterface.php
Labels: patch
